import hero from "../images/decoration/hero-logo3.png";
export const images = {
  heroImg: hero,
  reactImg:
    "https://drive.google.com/uc?export=view&id=1bhQUZ3p9P5NPLf7Dgu1fBpon3k-rTXeV",
  nextImg:
    "https://drive.google.com/uc?export=view&id=1R_gAL2BhmmCGWJi1ETMWh0tx6lWuW-4F",
  js: "https://drive.google.com/uc?export=view&id=1B7yHiPotFEJxUS26laiSkiNXLwCN9_0r",
  expressImg:
    "https://drive.google.com/uc?export=view&id=1UllN_nGUT9w2ioUH9-hLkalX91MP8FfZ",
  htmlImg:
    "https://drive.google.com/uc?export=view&id=1y21VySScY2jl2beyJAqWwJpBsEpZKaNL",
  cssImg:
    "https://drive.google.com/uc?export=view&id=1Mj8BfK363scG2MT431y7N0UMCCamgAZr",
  mongoImg:
    "https://drive.google.com/uc?export=view&id=1ZukQBHNRGajFiE4JpUT_DDSBRnF6ZaDS",
  nodeImg:
    "https://drive.google.com/uc?export=view&id=1U-ovxpCQImCroA5308gnoQJedaKU_8IF",
  reduxImg:
    "https://drive.google.com/uc?export=view&id=1ztVuue_8YfNISIZHvaTnXyVDQv3PaPat",
  npmImg:
    "https://drive.google.com/uc?export=view&id=1CjqLTWaW28H8a2nMDPJmIfQzM35AU2Nx",
  bootstrapImg:
    "https://drive.google.com/uc?export=view&id=12QLrFFpvDK3a7XCCVvlDPwVkZntAOZ0K",
  githubImg:
    "https://drive.google.com/uc?export=view&id=127-4fh5xI1a6smGKrxKJxlqDm115wrEb",
  gitlabImg:
    "https://drive.google.com/uc?export=view&id=1Bxp21VFExeDLaKNj81wDY8B2Dnhv4rhA",
  materialImg:
    "https://drive.google.com/uc?export=view&id=1Faj14rMwsk8PzdZR8T7-SDAd5rTIKwiw",
  firebaseImg:
    "https://drive.google.com/uc?export=view&id=1sE88-eHJTsc43UgcT-eASIT8IJgk9ory",
  evIndia:
    "https://drive.google.com/uc?export=view&id=1c3x40LNVPPMmAE3niN9xDY8WhHu17lV_",
  memories:
    "https://drive.google.com/uc?export=view&id=1xtpDR-2naxLvX9ycLkF8bU9BMFQq-M3B",
  mragain:
    "https://drive.google.com/uc?export=view&id=1K0AkvgR_NeITwxmGYZKrOysFDLJ_gUWZ",
  saturncube:
    "https://drive.google.com/uc?export=view&id=1oCOqVQdTUJ6165jFGGLNYnBntznySVtj",
  time2Enter:
    "https://drive.google.com/uc?export=view&id=1V7uNTzrSuy2PlCy9E8w5dB23cWN9j9fP",
  staffRoster:
    "https://drive.google.com/uc?export=view&id=1Gn34NO2VQ1-dWJ4EZ9xwDwe53SGcRYEx",
  elumat:
    "https://drive.google.com/uc?export=view&id=1mJGSg75gbOoWLmsq2hp1F5QsTz5dt-2L",
  portfolio:
    "https://drive.google.com/uc?export=view&id=1_kuo3BwmxicNplZDPJVv4hPTt3djdDo8",
};
